# Generated by Django 3.2 on 2021-10-09 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yishi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentp',
            options={'verbose_name_plural': 'commentPs'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='star_rating',
        ),
        migrations.AlterField(
            model_name='products',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.CreateModel(
            name='star_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.FloatField(default=0.0, max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('Pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yishi.products')),
            ],
        ),
    ]
