# Generated by Django 3.2 on 2021-10-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yishi', '0002_auto_20211010_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Photo',
            field=models.ImageField(default='NoImage.jpg', upload_to='images'),
        ),
    ]
