# Generated by Django 3.2 on 2021-10-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yishi', '0003_alter_products_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
