# Generated by Django 3.2 on 2021-10-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yishi', '0005_alter_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='star_rating',
            name='n',
            field=models.IntegerField(default=0),
        ),
    ]
