# Generated by Django 3.2 on 2021-10-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yishi', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(max_length=1024)),
                ('state', models.CharField(choices=[('ACTIVE', 'active'), ('DEALED', 'dealed'), ('UNACCEPTED', 'unaccepted')], default='ACTIVE', max_length=128)),
            ],
        ),
    ]
